ALPHA_VANTAGE_API_KEY = 'YOUR ALPHA VANTAGE API KEY'
SEC_API_KEY = 'YOUR SEC API KEY'

NEWS_SITE = 'https://www.bloomberg.com/markets'

TECH_STOCKS = ['MSFT', 'NVDA', 'AAPL', 'CSCO', 'ORCL', 'IBM']
